- name: MongoDB server
  hosts: storage
  become: yes
  user: vagrant
  gather_facts: false
  roles: 
  - thermostat-common
#  - mongodb

- name: JBoss EAP 6.4 server
  hosts: agent1
  become: yes
  user: vagrant
  gather_facts: false
  roles:
  - thermostat-common
#  - thermostat-agent
  
- name: JBoss EAP 7.0 server
  hosts: agent2
  become: yes
  user: vagrant
  gather_facts: false
  roles:
  - thermostat-common
#  - thermostat-agent
  
- name: Generic Java app
  hosts: agent3
  become: yes
  user: vagrant
  gather_facts: false
  roles:
  - thermostat-common
#  - thermostat-agent