---
# tasks file for common
- name: Install python2 on the remote machine
  raw: dnf install -y python2 python2-dnf libselinux-python
 
- name: Gather facts
  setup:
  
- name: Setup OpenJDK
  dnf: name=java-1.8.0-openjdk,java-1.8.0-openjdk-devel state=latest
  
- name: Install thermostat
  dnf: name=thermostat state=latest